nodeLinker: node-modules
enableGlobalCache: true
networkTimeout: 600000
networkConcurrency: 1
npmRegistryServer: "https://registry.npmjs.org"
npmScopes:
  private:
    npmRegistryServer: "https://registry.npmjs.org"
unsafeHttpWhitelist:
  - "registry.npmjs.org"
  - "registry.yarnpkg.com"
enableScripts: true
enableTelemetry: false