[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "yarn start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[nixpacks]
node-version = "20"
install-cmd = "yarn install --network-timeout 100000"

[phases.setup]
nixPkgs = ["python3", "gcc", "g++", "make"] 